server:
  port: 7001
  servlet:
    context-path: /ad-search

spring:
  application:
    name: eureka-client-ad-search
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sunny_ad?autoReconnect=true
    username: root
    password: Djangobbs
    tomcat:
      max-active: 4
      min-idle: 2

feign:
  hystrix:
    enabled: true

#服务暴露，开启监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


